<?php

return [

    'items' => [
        [
            'name' => 'Users',
            'path' => '/userauth/users',
            'icon' => 'fas fa-user-friends',
            'customIcon' => false,
            'toolTip' => 'Users',
            'permission_type' => 'permission',
            'permission' => 'users.view',
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'User Roles',
            'path' => '/userrole/roles',
            'icon' => 'fas fa-user-tie',
            'customIcon' => false,
            'toolTip' => 'User Roles',
            'permission_type' => 'permission',
            'permission' => 'user-roles.view',
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'User Role Permissions',
            'path' => '/userrole/permissions',
            'icon' => 'fas fa-tasks',
            'customIcon' => false,
            'toolTip' => 'User Role Permissions',
            'permission_type' => 'permission',
            'permission' => 'user-role-permissions.view',
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Pickers',
            'path' => '/userrole/pickers',
            'icon' => 'fas fa-cart-arrow-down',
            'customIcon' => false,
            'toolTip' => 'Pickers',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Drivers',
            'path' => '/userrole/drivers',
            'icon' => 'fas fa-shuttle-van',
            'customIcon' => false,
            'toolTip' => 'Drivers',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Orders',
            'path' => '/sales/orders',
            'icon' => 'fas fa-shopping-cart',
            'customIcon' => false,
            'toolTip' => 'Orders',
            'permission_type' => 'role',
            'permission' => ['admin'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Regions',
            'path' => '/sales/regions',
            'icon' => 'fas fa-map-marked',
            'customIcon' => false,
            'toolTip' => 'Regions',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Sales Picklist',
            'path' => '/sales/picklist',
            'icon' => 'fas fa-list-ol',
            'customIcon' => false,
            'toolTip' => 'Sales Picklist',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Pickers Report',
            'path' => '/userrole/pickers-report',
            'icon' => 'fas fa-list',
            'customIcon' => false,
            'toolTip' => 'Pickers Report',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Drivers Report',
            'path' => '/userrole/drivers-report',
            'icon' => 'fas fa-list',
            'customIcon' => false,
            'toolTip' => 'Drivers Report',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Feeders Report',
            'path' => '/userrole/feeders-report',
            'icon' => 'fas fa-list',
            'customIcon' => false,
            'toolTip' => 'Feeders Report',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Yango Logistics Report',
            'path' => '/userrole/yango-logistics-report',
            'icon' => 'fas fa-list',
            'customIcon' => false,
            'toolTip' => 'Yango Logistics Report',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => true,
            'children' => null,
        ],
        [
            'name' => 'Update Stock',
            'path' => '/sales/stock-update',
            'icon' => 'fas fa-redo',
            'customIcon' => false,
            'toolTip' => 'Update Stock',
            'permission_type' => 'role',
            'permission' => ['admin', 'supervisor'],
            'active' => false,
            'children' => null,
        ],
        [
            'name' => 'POS System',
            'path' => '/sales/pos',
            'icon' => 'fas fa-calculator',
            'customIcon' => false,
            'toolTip' => 'POS System',
            'permission_type' => 'role',
            'permission' => ['admin', 'cashier'],
            'active' => false,
            'children' => null,
        ],
    ],

];
